NOJIRA |  uses krogo as micro framework
sumit-dhull/logisticstest pull request #3
Opened 2021-01-04 10:48 UTC by sumit-dhull

2021-01-04 10:57 UTC, cherry-rd commented
Test comment!

2021-01-04 11:08 UTC, ravikiran-zs requested changes

2021-01-04 11:08 UTC, ravikiran-zs commented on go.mod
go module path needs to be in the format <git-repo>/directory https://github.com/sumit-dhull/logisticstest/blob/36cf07d8e054ec8e49efc687ea4924f81680a727/go.mod

2021-01-05 05:08 UTC, sumit-dhull commented on go.mod
in the latest commit, I have addressed the formatting of go module path

2021-01-05 08:20 UTC, ravikiran-zs requested changes

2021-01-05 08:20 UTC, ravikiran-zs commented on configs/.local.env
> +DB_HOST=localhost
This should not be committed in the repo, should be in `.gitignore`. Rest is fine, you can Merge it with this change

2021-01-05 11:18 UTC, sumit-dhull commented on configs/.local.env
> +DB_HOST=localhost
Latest commits remove `.local.env` and adds the config file to `.gitignore`

2021-01-05 11:22 UTC, merged